// src/app/layout.tsx
'use client'

import { SessionWrapper } from './components/SessionWrapper'
import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Ticket7 Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>{children}</body>
      </html>
    </SessionWrapper>
  )
}
